linters-settings:
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 200
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - paramTypeCombine
      - unnamedResult

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gochecknoglobals

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals
        - gochecknoinits

service:
  golangci-lint-version: 1.27.x # use the fixed version to not introduce new linters unexpectedly