name: CI
on: push
jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Linter
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27