name: Linter
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run Linter
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27