name: lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: Run Linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44
